### ISSUE TITLE
🐞 [BUG] Syntax Error @Github Actions > docker-image.yml

### ISSUE THREAD

**Issue by wkdalsgh192** [InSSAFY/InIT_SpringBoot#21]
## Describe the bug
도커 이미지 배포 워크플로우 내 syntax 에러로 인해 PR 시 제대로 실행되지 않는 문제가 있습니다.

**Screenshots**
![image](https://user-images.githubusercontent.com/50606172/152669537-ff3c1b46-4f25-4cfb-b714-5997ac05d312.png)

**Comment by taejin0323** [comment]
여전히 에러가 발생하는 것 같아서 다시 열어놨습니당ㅠ

![image](https://user-images.githubusercontent.com/24222394/152669747-0c26cfc2-16a0-4015-bc88-350b1bef2b45.png)

이 부분이 문제 아닐까요?

**Comment by wkdalsgh192** [comment]
로컬에서는 문제가 없었는데 다시 한 번 확인해볼게요

**Comment by wkdalsgh192** [comment]
확인해봤는데 jobs:build:steps:run 에서 다중 커맨드 입력 시 파이프를 먼저 넣어주어야 했는데 이 부분을 빠뜨렸네요. 
develop 브랜치 PR 리버트 시키고 재 PR 하겠습니다. 
@taejin0323 님이 리뷰 한 번 해주시면 감사하겠습니다.
